use: "yaml" # change to mysql, if you want to use a mysql or mariadb database
methods:
  txt:
    domain-list: "./domain-list.yml" # Enter the path to the domain list
  mysql: # cannot be used at the moment
    server: "127.0.0.1" # enter Ip-adress
    port: 3306 # enter port number; default: 3306
    user: "root" # change to the user, you want to use
    password: "password" # change to the password for the database user
    database: "SubDomainCloud" # Change this, if you have set another database